version: "3.9"

services:
  kavita:
    image: kizaing/kavita:latest
    restart: unless-stopped
    container_name: kavita
    user: "${PUID}:${PGID}"
    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 300s
      retries: 3
      start_period: 30s
      timeout: 15s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.service=kavita"
      - "traefik.http.routers.kavita.tls=true"
      - "traefik.http.routers.kavita.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.kavita.entrypoints=websecure"
      - "traefik.http.services.kavita.loadbalancer.server.port=5000"
      - "traefik.http.routers.kavita.middlewares=authelia@docker"
    volumes:
      - ./manga:/manga
      - ./data:/kavita/config
    networks:
      - web_proxy

networks:
  web_proxy:
    external:
      name: web_proxy
