version: "3.9"

services:
  uptime_kuma:
    image: docker.io/louislam/uptime-kuma:1.23.4-alpine@sha256:43ad2d5792543325d65ec09a1a72353885e286cdf8f22b9d5b95f39ef2bd8db8
    container_name: uptime_kuma
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.uptime_kuma.loadbalancer.server.port=3001"
      - "traefik.http.routers.uptime_kuma.service=uptime_kuma"
      - "traefik.http.routers.uptime_kuma.tls=true"
      - "traefik.http.routers.uptime_kuma.entrypoints=websecure"
      - 'traefik.http.routers.uptime_kuma.rule=Host("$UPTIME_KUMA_HOST")'
      - "traefik.http.routers.uptime_kuma.middlewares=authelia@docker"
    networks:
      - web_proxy
    # No healthcheck because no public endpoint

networks:
  web_proxy:
    external: true
