version: "3.9"

services:
  uptime_kuma:
    image: docker.io/louislam/uptime-kuma:1.23.3-alpine@sha256:94b692d327224a0bcadf3e7affcd48d200f8cdf8b3d4949540677ac388b3e40c
    container_name: uptime_kuma
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime_kuma.service=uptime_kuma"
      - "traefik.http.routers.uptime_kuma.tls=true"
      - "traefik.http.routers.uptime_kuma.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.uptime_kuma.entrypoints=websecure"
      - "traefik.http.services.uptime_kuma.loadbalancer.server.port=3001"
      - 'traefik.http.routers.uptime_kuma.rule=Host("$UPTIME_KUMA_HOST")'
      - "traefik.http.routers.uptime_kuma.middlewares=authelia@docker"
    networks:
      - web_proxy

networks:
  web_proxy:
    external: true
