version: "3.9"

services:
  syncthing:
    image: docker.io/linuxserver/syncthing:1.25.0@sha256:e76d3d3abfce2f7ef788a6c2af28d4fecfabb8d191ace6a4ad7e1496d1b9a5ea
    container_name: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${SYNCTHING_DATA_PATH}:/mnt/syncthing
    ports:
      - ${SYNCTHING_PORT}:22000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.http.routers.syncthing.service=syncthing"
      - "traefik.http.routers.syncthing.tls=true"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - 'traefik.http.routers.syncthing.rule=Host("$SYNCTHING_HOST")'
      - "traefik.http.routers.syncthing.middlewares=authelia@docker"
    networks:
      - web_proxy
    # No healthcheck because no public endpoint

networks:
  web_proxy:
    external: true
